name: ipoolseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcbiogff>=0.6.4
  - biopython>=1.73
  - bzip2
  - conda-ecosystem-user-package-isolation
  - curl
  - fastqc>=0.11
  - gawk>=5
  - namedlist>=1.7
  - nextgenmap=0.5.5
  - picard>=2.20
  - pysam>=0.15
  - bioconductor-rtracklayer>=1.42
  - r-data.table>=1.12
  - r-dt
  - r-gwpcr>=0.9.10
  - r-markdown
  - samtools>=1.9
  - snakemake>=5.4.5
  - trimmomatic=0.39
  - trumicount>=0.9.13
  - umi_tools=0.5.5
